### ISSUE TITLE
Add support for MQTT over WebSocket

### ISSUE THREAD

**Issue by alibo** [goiiot/libmqtt#20]
Could you please add support for MQTT over WebSocket as well? Is this on your plan? (I've already searched the docs but I couldn't find it. If it's already implemented, please ignore it and close this issue :D)

**Comment by jeffreystoke** [comment]
Hi @alibo , sorry for the late reply. We didn't implement mqtt over websocket since that's not wire efficient for non browser application, we would probably provide some options like `WithServerURL` to designate a transport layer protocol (e.g. `tcp`, `quic`, `kcp`, and of course, `websocket`) with server address and replace the current `WithServer` and `WithSecureServer` in near future.

**Comment by jeffreystoke** [comment]
@alibo WebSocket based MQTT connection is now available at branch [feature/mqtt5](https://github.com/goiiot/libmqtt/tree/feature/mqtt5), here are some sample code:

```go
c, err := NewClient(WithLog(Verbose))
// check client creation error

err = c.ConnectServer("localhost:8083/mqtt",
	WithWebSocketConnector(0, nil),
)
// check if any option error
```

Feel free to ask any question about this project.

Have a nice day ;)

**Comment by alibo** [comment]
It's great, thanks :)
