### ISSUE TITLE
new connection not always successful.

### ISSUE THREAD

**Issue by jimu-liubin** [goiiot/libmqtt#36]
create a connection to server. Trying to to the following steps.

1. ctrl + c
2. restart the code

repeat above code for couple times, then got the following error.

error happened to connection to server [localhost:1883]: EOF

Please note that  defer client.Destroy(true) is already added.  The error happens quite random, sometimes 2-3 times, sometimes just once.

**Comment by jeffreystoke** [comment]
Hi @jimu-liubin , this behaviour is probably caused by the `client-id` collision in the mqtt broker, most mqtt broker won't allow duplicated `client-id` from different connections, and according to the standard, a mqtt broker must close connection in this case.

Just in case of that, can you make sure that the `client-id` you use for new connection doesn't present in mqtt broker when you connect to the broker?

Thanks!

**Comment by Xraider42** [comment]
I tried using the library and I hit the same issues on both MQTT V5 and V3.11

Out of 10 connections, 6-7 are successful. VerneMQ complains about not being able to parse the connect parser, mosquitto just dies with a generic socket error log. 

Using the branch from https://github.com/goiiot/libmqtt/pull/28 solved these issues. 

Furthermore, V5 is a bit broken - VerneMQ complains about a missing version header. Did not try other V5 compliant brokers. 

I can confirm its not the client-id as i regenerate a random 8 byte hex client id on every connection during my test runs.

**Comment by jeffreystoke** [comment]
Hi @Xraider42 , thanks for your attention, I will inspect the pr and fix this soon, but v5 support is not complete now, I'm planning to release v5 support in v1.x, which would take some time.

**Comment by jeffreystoke** [comment]
I'm not so sure the root cause of this issue, but it seems caused by the buffered connection not flushed in time, I will merge that pull request, thank you again @Xraider42 and @jimu-liubin .

BTW, @Xraider42 can you open another issue about the v5 issue, I finally got some time working on this recently, thanks!
